### ISSUE TITLE
Fix lint checking errors

### ISSUE THREAD

**Issue by ocrosby** [ocrosby/futbol-means#4]
Currently I am seeing a lint checking error stating

Error: Failed to load config "@ljharb" to extend from.

I need this to go away.

**Comment by ljharb** [comment]
That means you’re linting node_modules, which you should never do. Try `eslint .` instead of passing a glob.

**Comment by ocrosby** [comment]
I found that eslint appeared to be trying to analyse node modules from the dist directory so to address that I added /node_modules, dist, and my cucumber.js features directory to the .eslintignore file.  This appears to have resolved the issue.
